### ISSUE TITLE
Change code of conduct and CVD link on website

### ISSUE THREAD

**Issue by G360DAO** [G360DAO/g360dao-io#12]

**Comment by jmbguardian360io** [comment]
Link Coordinated Vulneraility disclosure link in the footer to https://code-of-conduct.g360dao.io/cvd

Change 'code of conduct' to 'rules of engagement' on the Getting Started page and link it to https://code-of-conduct.g360dao.io/rules-of-engagement

**Comment by Zeichnicht** [comment]
applied to InvestPage.vue, JoinTheRevolution.vue, SecurityInsights.vue
